import mammoth from 'mammoth';

export interface ParsedDocument {
  text: string;
  pages: { pageNumber: number; text: string }[];
  totalPages: number;
}

export interface Chunk {
  id: string;
  pageNumber: number;
  section: string;
  text: string;
}

export async function parseDocumentBuffer(
  buffer: Buffer,
  fileType: string
): Promise<ParsedDocument> {
  const normalizedType = fileType.toLowerCase();

  if (normalizedType.includes('pdf')) {
    return parsePdfBuffer(buffer);
  } else if (normalizedType.includes('word') || normalizedType.includes('docx') || normalizedType.includes('document')) {
    return parseDocxBuffer(buffer);
  } else {
    // Default to plain text
    const text = buffer.toString('utf-8');
    return createPagesFromText(text);
  }
}

async function parsePdfBuffer(buffer: Buffer): Promise<ParsedDocument> {
  try {
    // Lazy require pdf-parse inside function scope to prevent top-level DOMMatrix evaluation errors during Next.js build
    const pdfParse = require('pdf-parse');
    const data = await pdfParse(buffer);
    const rawText = data.text || '';
    
    // Split by form feeds or page marker heuristics if available
    const pageSplits = rawText.split(/\f|\n(?=--- PAGE \d+ ---|\f)/i);
    
    if (pageSplits.length > 1) {
      const pages = pageSplits.map((pageText: string, idx: number) => ({
        pageNumber: idx + 1,
        text: pageText.trim(),
      })).filter((p: { text: string }) => p.text.length > 0);

      return {
        text: rawText,
        pages,
        totalPages: data.numpages || pages.length || 1,
      };
    }

    // Otherwise split text roughly into 1800 character logical page chunks preserving sentences
    return createPagesFromText(rawText, data.numpages);
  } catch (error) {
    console.error('PDF parsing error:', error);
    throw new Error('Failed to parse PDF file. Please ensure it is a valid text-based PDF document.');
  }
}

async function parseDocxBuffer(buffer: Buffer): Promise<ParsedDocument> {
  try {
    const result = await mammoth.extractRawText({ buffer });
    const rawText = result.value || '';
    return createPagesFromText(rawText);
  } catch (error) {
    console.error('DOCX parsing error:', error);
    throw new Error('Failed to parse DOCX file. Please verify the document format.');
  }
}

function createPagesFromText(text: string, expectedPages?: number): ParsedDocument {
  const cleanText = text.trim();
  if (!cleanText) {
    return { text: '', pages: [{ pageNumber: 1, text: '' }], totalPages: 1 };
  }

  // Look for explicit "--- PAGE X ---" markers if generated by our system or sample
  const pageRegex = /--- PAGE (\d+) ---/g;
  if (pageRegex.test(cleanText)) {
    const parts = cleanText.split(/--- PAGE \d+ ---/);
    const pageNumbers = Array.from(cleanText.matchAll(/--- PAGE (\d+) ---/g)).map(m => parseInt(m[1], 10));
    
    const pages: { pageNumber: number; text: string }[] = [];
    parts.forEach((part, idx) => {
      const textChunk = part.trim();
      if (textChunk) {
        const pageNum = pageNumbers[idx - 1] || idx;
        pages.push({ pageNumber: pageNum, text: textChunk });
      }
    });

    if (pages.length > 0) {
      return {
        text: cleanText,
        pages,
        totalPages: expectedPages || pages.length,
      };
    }
  }

  // Fallback: Partition every ~1800 characters at double newline or period boundaries
  const chunkSize = 1800;
  const pages: { pageNumber: number; text: string }[] = [];
  let currentPos = 0;
  let pageCount = 1;

  while (currentPos < cleanText.length) {
    let nextPos = currentPos + chunkSize;
    if (nextPos >= cleanText.length) {
      nextPos = cleanText.length;
    } else {
      // Find clean sentence or paragraph boundary
      const boundary = cleanText.indexOf('\n\n', nextPos - 200);
      if (boundary !== -1 && boundary < nextPos + 200) {
        nextPos = boundary + 2;
      } else {
        const periodBoundary = cleanText.indexOf('. ', nextPos - 100);
        if (periodBoundary !== -1 && periodBoundary < nextPos + 100) {
          nextPos = periodBoundary + 2;
        }
      }
    }

    const pageText = cleanText.substring(currentPos, nextPos).trim();
    if (pageText) {
      pages.push({ pageNumber: pageCount, text: pageText });
      pageCount++;
    }
    currentPos = nextPos;
  }

  return {
    text: cleanText,
    pages,
    totalPages: expectedPages || pages.length || 1,
  };
}

export function chunkDocument(doc: ParsedDocument): Chunk[] {
  const chunks: Chunk[] = [];
  let chunkIdx = 1;

  doc.pages.forEach((page) => {
    const sectionLines = page.text.split('\n');
    let currentSection = `Page ${page.pageNumber}`;

    let paragraphAccumulator = '';

    sectionLines.forEach((line) => {
      const trimmed = line.trim();
      const sectionMatch = trimmed.match(/^(SECTION \d+:?|\d+\.\s+[A-Z\s]{3,})/i);
      
      if (sectionMatch) {
        if (paragraphAccumulator.length > 100) {
          chunks.push({
            id: `chunk-${chunkIdx++}`,
            pageNumber: page.pageNumber,
            section: currentSection,
            text: paragraphAccumulator.trim(),
          });
          paragraphAccumulator = '';
        }
        currentSection = trimmed;
      }

      paragraphAccumulator += line + '\n';

      if (paragraphAccumulator.length > 800) {
        chunks.push({
          id: `chunk-${chunkIdx++}`,
          pageNumber: page.pageNumber,
          section: currentSection,
          text: paragraphAccumulator.trim(),
        });
        paragraphAccumulator = '';
      }
    });

    if (paragraphAccumulator.trim().length > 0) {
      chunks.push({
        id: `chunk-${chunkIdx++}`,
        pageNumber: page.pageNumber,
        section: currentSection,
        text: paragraphAccumulator.trim(),
      });
    }
  });

  return chunks;
}
